use flo_draw::*;
use flo_draw::draw_scene::*;
use flo_draw::canvas::scenery::*;
use flo_scene::*;
use flo_scene::programs::*;
use flo_scene_binding::*;
use flo_binding::*;

use futures::prelude::*;

use std::sync::*;

///
/// The ID of the subprogram that processes `DrawingRequest` messages
///
pub fn subprogram_window() -> SubProgramId {
    SubProgramId::called("flo_ui::window")
}

///
/// Creates a scene containing a flo_draw window. This is a separate scene containing just the window, managed
/// by the main flo_draw scene.
///
/// Send drawing requests to thw window using `DrawingRequest` with the default target. Connect `DrawEvent` to 
/// your subprogram to receive events, or set up focus events by talking to Focus for cases where there
/// are many subprogram cooperating within a single window.
///
pub fn create_window_scene(window_properties: impl Into<WindowProperties>) -> Arc<Scene> {
    let window_properties = window_properties.into();

    // The window itself runs as a subprogram within the flo_draw scene
    let flo_draw_scene = flo_draw_scene_context();

    // Create a scene to run the window in with the default set of subprograms
    let window_scene = Arc::new(Scene::default());

    // The drawing program is the target for the drawing instructions for the window in the main scene
    let drawing_program_id = SubProgramId::new();

    // The event relay program receives events generated by the window and forwards them to our window scene
    let event_relay_program_id = SubProgramId::new();

    // The windows properties program sets the window properties for window
    let window_properties_program_id = SubProgramId::new();

    // Create the render window
    create_render_window_sub_program(&flo_draw_scene, drawing_program_id, window_properties.requested_size().get()).unwrap();

    // We use a binding program to send the window properties to the target window
    flo_draw_scene.add_subprogram(window_properties_program_id, move |input, context| window_properties_program(input, context, window_properties, drawing_program_id), 1);

    // The window scene program configures and runs the actual window scene (it runs in the main scene)
    let window_scene_program = SubProgramId::new();
    let running_window_scene = window_scene.clone();

    flo_draw_scene.add_subprogram(window_scene_program, move |_input: InputStream<()>, context| async move {
        // Add a subprogram in the window scene that relays drawing instructions from the window scene to the drawing window (as the window runs in the 'main' scene, we don't have access here)
        let drawing_requests = context.send::<DrawingWindowRequest>(drawing_program_id).unwrap();
        running_window_scene.add_subprogram(subprogram_window(), move |input, context| drawing_relay_program(drawing_requests, input, context), 100);

        // Allow drawing requests to be sent directly to the window
        let drawing_request_filter = FilterHandle::for_filter(|drawing_requests| drawing_requests.map(|req| DrawingWindowRequest::Draw(req)));
        running_window_scene.connect_programs((), StreamTarget::Filtered(drawing_request_filter.clone(), subprogram_window()), StreamId::with_message_type::<DrawingRequest>()).unwrap();

        // Forward events from the window to whatever program wants to receive them in the window scene
        let drawing_events      = running_window_scene.send_to_scene(()).unwrap();
        flo_draw_scene_context().add_subprogram(event_relay_program_id, move |input, context| event_relay_program(drawing_events, input, context), 20);

        context.send(drawing_program_id).unwrap()
            .send(DrawingWindowRequest::SendEvents(event_relay_program_id)).await.ok();

        // Run the window scene
        running_window_scene.run_scene_with_threads(4).await;

        // When the scene stops, also stop the window
        let drawing_requests = context.send::<DrawingWindowRequest>(drawing_program_id);
        if let Ok(mut drawing_requests) = drawing_requests {
            drawing_requests.send(DrawingWindowRequest::CloseWindow).await.ok();
        }

        // Stop the other programs we started in the scene
        context.send_message(SceneControl::Close(window_properties_program_id)).await.ok();
        context.send_message(SceneControl::Close(event_relay_program_id)).await.ok();
        context.send_message(SceneControl::Close(drawing_program_id)).await.ok();
    }, 1);

    // The window scene is ready to go
    window_scene
}

///
/// Program that relays events originating from the window in the app scene to the main document in the document scene
///
async fn event_relay_program(drawing_events: impl Unpin + Send + Sink<DrawEvent>, input: InputStream<DrawEvent>, _context: SceneContext) {
    let mut input           = input.ready_chunks(100);
    let mut drawing_events  = drawing_events;

    while let Some(event_chunk) = input.next().await {
        for event in event_chunk {
            drawing_events.send(event).await.ok();
        }
    }
}

///
/// Program that runs in the document scene and sends DrawingWindowRequests out to the application scene (where the actual window lives)
///
async fn drawing_relay_program(drawing_requests: OutputSink<DrawingWindowRequest>, input: InputStream<DrawingWindowRequest>, _context: SceneContext) {
    let mut drawing_requests = drawing_requests;
    let mut input            = input;

    while let Some(request) = input.next().await {
        // We can't wire up 'SendEvents' or similar messages here as they'll send their responses to the app scene, so we ignore them for now
        if let DrawingWindowRequest::SendEvents(_) = &request {
            // TODO: could start an event relay program here instead (we'd have to manage it and stop it when we're done though)
            continue;
        }

        // Pass the event on to the application scene
        let maybe_err = drawing_requests.send(request).await;

        if !maybe_err.is_ok() {
            break;
        }
    }
}

///
/// The window properties program updates the properties for a window dynamically
///
async fn window_properties_program(input: InputStream<BindingProgram>, context: SceneContext, window_properties: WindowProperties, drawing_window_id: SubProgramId) {
    // Binding reads the values from the properties
    let binding = computed(move || {
        (
            window_properties.title.get(),
            window_properties.fullscreen.get(),
            window_properties.has_decorations.get(),
            window_properties.mouse_pointer.get(),
            window_properties.viewport_bounds.get()
        )
    });

    // Action sets the values in the drawing program
    let last_title              = Arc::new(Mutex::new(None));
    let last_fullscreen         = Arc::new(Mutex::new(false));
    let last_has_decorations    = Arc::new(Mutex::new(true));
    let last_mouse_pointer      = Arc::new(Mutex::new(None));
    let last_viewport_bounds    = Arc::new(Mutex::new(None));

    let action = BindingAction::new(|(title, fullscreen, has_decorations, mouse_pointer, viewport_bounds): (String, bool, bool, MousePointer, ViewportBounds), context| {
        let last_title              = last_title.clone();
        let last_fullscreen         = last_fullscreen.clone();
        let last_has_decorations    = last_has_decorations.clone();
        let last_mouse_pointer      = last_mouse_pointer.clone();
        let last_viewport_bounds    = last_viewport_bounds.clone();

        async move {
            let Ok(mut drawing_window) = context.send(drawing_window_id) else { return; };

            if &Some(title.clone()) != &*last_title.lock().unwrap() {
                drawing_window.send(DrawingWindowRequest::SetTitle(title.clone())).await.ok();
                (*last_title.lock().unwrap()) = Some(title);
            }

            if fullscreen != *last_fullscreen.lock().unwrap() {
                drawing_window.send(DrawingWindowRequest::SetFullScreen(fullscreen)).await.ok();
                *last_fullscreen.lock().unwrap() = fullscreen;
            }

            if has_decorations != *last_has_decorations.lock().unwrap() {
                drawing_window.send(DrawingWindowRequest::SetHasDecorations(has_decorations)).await.ok();
                *last_has_decorations.lock().unwrap() = has_decorations;
            }

            if Some(mouse_pointer) != *last_mouse_pointer.lock().unwrap() {
                drawing_window.send(DrawingWindowRequest::SetMousePointer(mouse_pointer)).await.ok();
                *last_mouse_pointer.lock().unwrap() = Some(mouse_pointer);
            }

            if Some(viewport_bounds) != *last_viewport_bounds.lock().unwrap() {
                drawing_window.send(DrawingWindowRequest::SetViewportBounds(viewport_bounds)).await.ok();
                *last_viewport_bounds.lock().unwrap() = Some(viewport_bounds);
            }
        }
    });

    binding_program(input, context, binding, action).await;
}
